### PR TITLE
Some asserts

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by HechtiDerLachs** [comment]
copied from slack:

If anyone finds the time to look at this, try to run experimental/Geometry/test.jl and look at what you get there. The variables involved in the crash should be accessible in the repl in the tuple Oscar.Misc.crash.

Something fails that shouldn't fail. But curiously, when I try to reproduce the problem with the same ring and the same equations in another single file and I carry out the exact same computations, then it always works.Anyway: It would be nice if this could be fixed somehow. Again, the error passes through one call to simplify!(...) which has "# not necessary" as a comment behind it. So that would probably be the dirty way to 'solve' the issue.

**Comment by HechtiDerLachs** [comment]
Just to make sure we're all on the same page: The error that I get is 

ERROR: LoadError: Incorrect number of exponents in push_term!

and it occurs in experimental/Geometry/Misc.jl:162

**Comment by HechtiDerLachs** [comment]
Ok, thanks to Tommy's investigation, the error was spotted. Interestingly, it was caused before the divide command was called. The two arguments passed on to divide (cached in Oscar.Misc.crash) both do have the same parent. However, I overlooked that in experimental/Geometry/Schemes.jl:763 the argument f passed on two proj_loc is not an element of the ring S_t. But then the projection proj_loc should complain! And not pretend to do its job and then something else breaks later on. Right?

**Comment by thofma** [comment]
https://github.com/oscar-system/Oscar.jl/pull/678 goes in this direction.

**Pull request merged**
